### ISSUE TITLE
Not for 4.2.2

### ISSUE THREAD

**Issue by Puklinae** [sci-comp/SceneBuilder#21]
It's not working in 4.2.2 but works in other versions of Godot can you please update <3

**Comment by sci-comp** [comment]
Hmm, it sure doesn't work for 4.2.2 anymore, I can't remember what changed offhand. I think it's something to do with how the raycast is being handled.

I imagine the solution here will be to create an `if/else` together with [get_version_info](https://docs.godotengine.org/en/stable/classes/class_engine.html#class-engine-method-get-version-info) inside the method `perform_raycast_with_exclusion` in script `scene_builder_dock.gd`, but I'm not sure. I'll have to spend a bit more time on this soon.

I'm currently working in 4.3.rc1, though I would not recommend this version. There's was a performance reimport regression, though that seems to already be fixed in 4.3rc3, which I will be upgrading to soon!

**Comment by Puklinae** [comment]
sounds good thanks for responding!

**Comment by sci-comp** [comment]
Thank you so much Guilherme, looks great! The whitespace changes are definitely appreciated as well, I didn't mean to stray from GDScript convention.

Please reopen the issue if there's still a problem @Puklinae!
