### ISSUE TITLE
Cannot rotate placing object

### ISSUE THREAD

**Issue by beef331** [sci-comp/SceneBuilder#4]
The object is always placed axis aligned and there is no way for the user to rotate whilst placing.
Ideally there would be a keybind to do rotation in 90 degree increments and a way to do free rotations.

**Comment by sci-comp** [comment]
We should be able to press keys 1-3 to enter rotation mode, 4 for scale, and 5 to reset orientation. Does this not work for your testing?

Rotations are always applied in world space. I will add a local rotation option soon.

**Comment by sci-comp** [comment]
Hmm, it looks like 5 doesn't reset scale, but it does reset rotation for me. I think that behavior makes sense since it's pretty easy to rescale the object, but difficult to reset the orientation.

When we rotate or scale the object, we press left click to apply the rotation to the preview item. Then 5 to reset orientation.

**Comment by sci-comp** [comment]
Aha! I I see what you mean! 

It should be fixed now. I'll open a new issue for the local rotation option I mentioned above.
